---
- name: Stop the eagledrive stack
  community.docker.docker_compose_v2:
    project_src: "{{ eagledrive_base_path }}/src"
    state: absent
  when: (eagledrive_base_path ~ '/src/docker-compose.yml') is exists
  ignore_errors: true
